### ISSUE TITLE
[Modpack Problem]: FTB App Issue

### ISSUE THREAD

**Issue by HarryC621** [FTBTeam/FTB-University#109]
* What version of University: 1.1.1
* Describe the issue: [](url)
When installing, it came out strange and looked like this screenshot. When I started a world it showed the questbook as random strings of code. 
![unknown](https://user-images.githubusercontent.com/73643428/97559008-cc859600-19d4-11eb-8a49-21424a2d73e1.png)

**Comment by aaronhowser1** [comment]
This should be on https://github.com/FTBTeam/FTB-App/issues/, not here,
since its an issue with the App
