### ISSUE TITLE
[Modpack Problem]: Recipe for Lexica Botania and Forester's Manual conflicts

### ISSUE THREAD

**Issue by n30phyte** [FTBTeam/FTB-University#112]
* What version of University: 1.1.1
* Describe the issue: Book+treeSapling shapeless recipe produces both mentioned items.

**Comment by desagas** [comment]
Can confirm. There is no way to switch between them when using saplings. You will have to usea honey drop or any forestry/gendustry drop to make it.

**Comment by desagas** [comment]
Update, this manual is found in the introductions quest line and does not need to be crafted, it is given to you for simply checking a box.
