### ISSUE TITLE
[Mod Request]: Lost Cities

### ISSUE THREAD

**Issue by SissyFemBoi** [FTBTeam/FTB-University#114]
* Mod Name: The Lost Cities
* Mod Dependencies: None
* Mod License:MIT License
* Mod Link: https://www.curseforge.com/minecraft/mc-mods/the-lost-cities
* Why you want it: it would easier to get stuff for players who are just comes from easy packs like FTB Academy,ETC... to medium defficulty packs so they don't wont to get frustrated looking for stuff

**Comment by aaronhowser1** [comment]
Lost Cities is literally already in

**Comment by aaronhowser1** [comment]
It can only be reached using Advanced Rocketry, but it 100% is already in

**Comment by SissyFemBoi** [comment]
I am deeply sorry that I did not notice lost cities was already in the pack, from now on I will look batter what mods are in before I will maybe suggest a mod to be added.

I feel Really bad that I suggested a mod that was in already

**Comment by aaronhowser1** [comment]
It's fine lol, don't worry about it
