### ISSUE TITLE
[Quest Problem]: IC2 i/o upgrades don't register

### ISSUE THREAD

**Issue by SneakyPika** [FTBTeam/FTB-University#129]
* What version of University: 1.1.0
* What quest: Items Come In, Items Go Out, You Can't Explain That
* What is the problem: Neither the fluid or items ejector or pulling upgrades are registering for the quest. I made all 4 and none of them worked.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/98365697-66ae9500-1ff8-11eb-8c85-05a60e7211cb.png)
![image](https://user-images.githubusercontent.com/15698722/98365740-75954780-1ff8-11eb-8002-ac4f6404b3c5.png)
Cannot reproduce

**Comment by SneakyPika** [comment]
I crafted them multiple times and it didn't work, triggered after putting into a machine and taking it out if anyone else has the issue.
