### ISSUE TITLE
[Modpack Problem]: Quark Oddities Enchantment Matrix Redundancy

### ISSUE THREAD

**Issue by LectroStatic1** [FTBTeam/FTB-University#134]
* What version of University: 1.1.0
* Describe the issue: 
In the enchanting table there are a few enchantments that can get rolled that have (too) similar effects, eg. XP Boost (from ender IO) vs Insight (From COFHCore), and Smelting (from COFHCore) vs autosmelt (Endercore). As you can only get a limited amount of pieces in the matrix, I think it'd be less frustrating to have either of them to be excluded from the possible enchantments in the Matrix by default.

This, and I personally think enchantments like smelting/crushing/salvage take up too much of the little chance you have already for your desired enchantments to appear. However, I think if the redundant enchantments are removed it'll be a lot more enjoyable to use the enchantment Matrix.

Of course, as client/server you can easily edit this in the quark config file.

**Comment by aaronhowser1** [comment]
Removed:
Random Things' Magnetic, kept Charm's
EnderCore's XP Boost, kept Thermal's
EnderCore's Smelting, kept Thermal's
