### ISSUE TITLE
[Modpack Problem]: Server won't install

### ISSUE THREAD

**Issue by CodeMastr3** [FTBTeam/FTB-University#138]
* What version of University: 1.1.1
* Describe the issue: Every time I try to install the server via the exe, for windows, it only gets to around ~4000/7000 and then gives me a ran out of memory error
java.lang.outofmemoryerror could not allocate an aligned heap chunk
This isn't a problem with ram because my total ram usage only gets to roughly 50% when monitoring in task manager.

**Comment by aaronhowser1** [comment]
Put on FTB App tracker, not here
