### ISSUE TITLE
[Modpack Problem]: Forge mod loader detected that the backup level.dat is being used.

### ISSUE THREAD

**Issue by markgyoni** [FTBTeam/FTB-University#141]
* What version of University: 1.1.1
* Describe the issue:  After updating from 1.0 to 1.1.1 when I open my world that's created in 1.0 it says: 
Forge mod loader detected that the backup level.dat is being used.
When I make a backup and load the world some of the blocks are missing or they are deleted.
I added BonsaiTrees2, Refined Storage, Refined Storage Additions, Reborn Storage, Refined Storage Requestify, Refined Storage Infinite Wireless

[latest.log](https://github.com/FTBTeam/FTB-University/files/5470842/latest.log)

**Comment by aaronhowser1** [comment]
Your download might have corrupted or something. Re-install and load a backup of the world.

**Comment by markgyoni** [comment]
I reinstalled it fully and it's the same.
Maybe it got corrupted at a saving. So I lost it all.
