### ISSUE TITLE
[Quest Problem]: Mention ticks per operation setting in Integrated Dynamics questline

### ISSUE THREAD

**Issue by squuig** [FTBTeam/FTB-University#143]
* What version of University: 1.1.1
* What quest: Readers or Item Transfer (probably)
* What is the problem: People seem to be having issues with performance caused by Integrated Dynamics Readers, Item Interfaces, Tunnels, etc having the default ticks per operation setting set to 1, causing tick lag. Might want to mention that, depending on their purpose (such as in the case of mass storage or anything that isn't sensitive to timing), ticks per operation can and probably should be set higher.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/97955771-99445d80-1d6c-11eb-85ad-060e786590cf.png)
