### ISSUE TITLE
[Mod Request]: Animus

### ISSUE THREAD

**Issue by CoconutPro** [FTBTeam/FTB-University#144]
* Mod Name: Animus
* Mod Dependencies: Blood Magic
* Mod License: (sorry I cant find it)
* Mod Link: https://www.curseforge.com/minecraft/mc-mods/animus
* Why you want it: "this mod adds more rituals and sigils to increase the quality of life as you play venture into Blood Magic". especially this mod adds ritual of culling which can kill mobs for blood generation instead of damaging them which is a very balanced and server friendly kind of thing.

**Comment by ValkyrieViolet** [comment]
Mod License: 
Creative Commons Attribution 4.0 International

http://creativecommons.org/licenses/by/4.0/
