### ISSUE TITLE
[Mod Problem]: Major Nether TPS Lag with Lumen

### ISSUE THREAD

**Issue by desagas** [FTBTeam/FTB-University#145]
* What version of University: 1.1.1
* What mod: lumen-Beta 0.4.1
* Have you made an issue on their issue tracker: No
* If so, link it here: 
* Describe the issue: My tick time drops from 8 or 9 in a OTG BB world to between 88 and 98 while in the nether. While using lag goggles, 216% taken by lumen:EntityEmbers. The next biggest taker is pigZombie at only 12%. It might be worthwhile to decrease or disable them.

**Comment by aaronhowser1** [comment]
216% of the lag? Over 100%?

**Comment by desagas** [comment]
Top upper right box in "world" in lag goggles. I’m not 100% sure how the number is calculated. Entities by Type. If it is not Ember, they are replaced with Firefly in by the same mod, to where the mod adds almost or slight over 100000 nano seconds no matter where I am in the nether, around fire and lava or not.

**Comment by desagas** [comment]
Actually, in my nether there are currently 512 actively loaded entities, the vast majority of which are embers and fireflies. I tried to download the log of lag goggles, but cant fint the log, I can post it if you tell me where it is located in the file system.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/97958829-ab75ca00-1d73-11eb-84f9-e6052f0a88fb.png)

Can confirm. Sad, because they really add to the ambience.
