### ISSUE TITLE
Slime too rare for medium use of Integrated Dynamics

### ISSUE THREAD

**Issue by borg286** [FTBTeam/FTB-University#146]
Integrated Dynamics makes heavy use of the Input Variable Transformer and the Output Variable Transformer. It is a blocker for having a Integrated Dynamics inventory management system. The Input Variable Transformer requires a Sticky Piston, which requires a slime ball.  These slime balls are hard to find. Slime chunks are rare, and frogs/beetles are small and also super hard to find.
In older modpacks I'd use riceballs and convert then to slime balls. These rice plants are fairly common on water pools overland. I'd like something as accessible in FTB University.

**Comment by aaronhowser1** [comment]
There's a bunch of ways to get slimes. The Slime Cube makes any chunk a slime chunk, and you can set up a regular mob grinder there. ID does not balance itself around having rice balls.
