### ISSUE TITLE
[Modpack Problem]: No Sound even after restart

### ISSUE THREAD

**Issue by JoelHud** [FTBTeam/FTB-University#149]
* What version of University:1.1.1.1
* Describe the issue: No Audio what-so-ever. No sound even in the Start screen. I am using the  headphone output on my Lenovo Laptop. YT makes sound, so sound works. All in game volume sliders at 100%. Game playable, but less enjoyable. Cheers!

**Comment by AutumnalModding** [comment]
Can you provide the `latest.log` file using gist (https://gist.github.com), please?

**Comment by JoelHud** [comment]
Public Gist created, Hope this helps. BTW Sound now works with no changes by me, except sleeping one day.

**Comment by aaronhowser1** [comment]
You need to link us to it lol

**Comment by JoelHud** [comment]
Aaron, sory NOOB troublefinder 😇

**Comment by aaronhowser1** [comment]
Yeah but... no. Link us the gist (or don't, since it's apparently fixed, but then close it in that case).

**Comment by JoelHud** [comment]
Thanks for trying. I think I need to do some studying. 😷👈👍
