### ISSUE TITLE
[Crash]: CLIENT Crash on bonemeal use due to  OTG on server only

### ISSUE THREAD

**Issue by Electrofried** [FTBTeam/FTB-University#15]
* What version of University: 1.0.0
* Have you added any mods: not to client, yes to server
* If yes, which mods: server has discord integration mod and tick profiler
* Crash report link (preferably Pastebin etc, not the file):  
https://pastebin.com/we1BckMx (With laggoggles)
https://pastebin.com/3rGEbYX2  (With laggoggles disabled)                            
* What were you doing when the crash happened: Bone mealing wheat to grow
* Any other details: Server default world is set to Biome bundle + BOP (BBOP)

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/96371680-7be68100-1128-11eb-8535-63bc3e75acfb.png)
