### ISSUE TITLE
[Mod Request]: Open Blocks Elevator

### ISSUE THREAD

**Issue by NuclearDogs-1** [FTBTeam/FTB-University#150]
* Mod Name: Open Blocks Elevator
* Mod Dependencies: None
* Mod License: MIT License 
* Mod Link: https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator
* Why you want it: There are no single-block elevators in this pack, and originally I was going to suggest open blocks, but someone had already suggested it. I realized that open blocks could be seen as a little cheaty, and long with other mods that I call "Kitchen Sink" Mods, such as cyclic. So, I then realized that there was a way to get the elevator without open blocks, so I am here suggesting this mod.

**Comment by Paspartout** [comment]
You can use ender io travel anchors in the same way as these elevators without needing a staff of travelling by the way.
They are more expensive, requiring about a diamond per block and an alloy smelter setup for the pulsating iron, but they also allow you to travel horizontally.

**Comment by aaronhowser1** [comment]
Denied; they're too easy and remove any reason to use Elevators from RFTools, PNC, EIO, etc.
