### ISSUE TITLE
[Mod Problem]: Magic Bees won't Produce AE2 Drops

### ISSUE THREAD

**Issue by desagas** [FTBTeam/FTB-University#151]
* What version of University: 1.1.1
* What mod: Magic Bees
* Have you made an issue on their issue tracker: No
* If so, link it here: 
* Describe the issue: The Silicon, Certus, Fluix ... bees have no products, even though both mods are in the pack. At first, I thought it was just a JEI issue showing drops, but once trying the bees themselves, they do not produce anything but normal forestry combs.

**Comment by aaronhowser1** [comment]
Duplicate of #32
