### ISSUE TITLE
Agricraft - Multiple Game Server Crash (Not full client crash, just world crash)

### ISSUE THREAD

**Issue by Eacaw** [FTBTeam/FTB-University#157]
Pack version 1.1.1

Two things to note here:

1) Trying to open the JEI for the recipe for melon seeds with agricraft crop sticks causes a game crash every time, regardless of path to reach the recipe.

2) Breaking a mature potato crop on crop sticks caused another world crash, and now the world won't load in, once loading is done  and it displays "Joining world..." it instantly crashes the world and brings me back to title screen. Full crash report here: https://pastebin.com/vfbzmJsa

Issue 1 is repeatable, have tested in a new world in creative and survival.

**Comment by Paspartout** [comment]
Yeah it's pretty annoying for me too.
I think removing Agricraft would be a good idea, since it seems pretty unstable and lead to crashes for me too.
I am thinking about removing it myself but am worried that all my seeds and crops are going to be gone.

**Comment by aaronhowser1** [comment]
All your Agricraft stuff will be gone, but nothing from other mods.

And yeah, I think I might have to remove it unfortunately. Super buggy.

**Comment by aaronhowser1** [comment]
Agricraft is being removed in 1.2
