### ISSUE TITLE
[Mod Request]:  Astral Sorcery

### ISSUE THREAD

**Issue by SK808** [FTBTeam/FTB-University#161]
* Mod Name: 
* Mod Dependencies: 
* Mod License:
* Mod Link:
* Why you want it:

There is more tech packs than magic packs and i think we need more and astral sorcery would be a nice way to get new structures into the world as well

**Comment by aaronhowser1** [comment]
It was taught in Academy, so no.

**Comment by SK808** [comment]
it doesnt matter tough because some people dont do academy they just do university
