### ISSUE TITLE
[Mod Request]: 

### ISSUE THREAD

**Issue by SK808** [FTBTeam/FTB-University#162]
* Mod Name: 
* Mod Dependencies: 
* Mod License:
* Mod Link:
* Why you want it:

There is more tech packs than magic packs and i think we need more and astral sorcery would be a nice way to get new structures into the world as well

**Comment by SK808** [comment]
some people dont do academy and university
they sometimes do only uniersity

**Comment by aaronhowser1** [comment]
Do not repost issues or you will be banned from making any.
