### ISSUE TITLE
Quest Suggestion: Add Projector to Immersive Engineering Chapter

### ISSUE THREAD

**Issue by natebc** [FTBTeam/FTB-University#172]
The projector can be crafted with the engineers manual (including akashic version) to project in world the multi-block that the manual is currently viewing.

It's VERY useful for putting together the Immersive machines.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/98482972-84335880-21ca-11eb-99f5-bc351fdc051f.png)
