### ISSUE TITLE
FPS-Problems in the nether

### ISSUE THREAD

**Issue by CodingJawa** [FTBTeam/FTB-University#174]
I have a massive fps drop in the nether as opposed to the overworld.
It drops to 2 fps, eating the 7 GB ram i provided for the game. Even setting render distance lower and reducing graphics quality to fast will not help with fps.
As I cannot allocate more ram i am out of options, what can i do? Is there anything in the nether that can cause such massive fps drop?

**Comment by Paspartout** [comment]
Probably related/duplicte to this: https://github.com/FTBTeam/FTB-University/issues/145

I would try disabling Lumen, as its causing major lab in the nether.

**Comment by aaronhowser1** [comment]
Lumen will be removed in 1.2
