### ISSUE TITLE
[Modpack Problem]: Singularities have to use the same item as the first inserted, rather than accepting any from the ore dictionary term

### ISSUE THREAD

**Issue by SneakyPika** [FTBTeam/FTB-University#177]
* What version of University: 1.1.0
* Describe the issue: Enriching Factory gives Thaumcraft amber but we need bop amber for singularities. JAPOCA overrides the crafting recipe to convert from Thaum to BOP so you can't easy convert between the two.

**Comment by SneakyPika** [comment]
You can use a conversion upgrade from drawers, but issue still should be fixed.

**Comment by aaronhowser1** [comment]
Added recipe to convert them.

Also, EC requires `ore:gemAmber` for Singularities. Are you sure TC Amber isn't working? Can you show a screenshot of it?

**Comment by SneakyPika** [comment]
I can look tomorrow, it might be able to accept it but not both at the same time. Didn't think about that.

**Comment by aaronhowser1** [comment]
Confirmed, you can only use the same item.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/98482748-0c186300-21c9-11eb-9316-39bf4f483041.png)
This is pretty much all I can do, unfortunately.
