### ISSUE TITLE
[Mod Problem]: Golden Lasso misplacing mobs

### ISSUE THREAD

**Issue by felda** [FTBTeam/FTB-University#18]
* What version of University: 1.0.0
* What mod: Extra Utilities 2
* Have you made an issue on their issue tracker: No
* If so, link it here: 
* Describe the issue: When placing a mob far away from where it was golden lasso'd the mob immediately disappeared. When placing a mob close to where i was golden lasso'd the mob is not able to be interacted with by the player or blocks (it walks through walls.) After a period of time it seems to update and teleport to where it was grabbed from. Happened in single player survival.

**Comment by random51** [comment]
Can confirm this with golden lasso. Brought two chickens home with lassos, they both disappeared immediately after being released.

Also saw similar behavior with the cloning machine from Advanced Genetics. Clone a squid from a scraping, it disappears a split second after it appears. Not every time, but most times.

**Comment by ToastedPT** [comment]
Can also confirm. Lasso just straight up does not work. Tried even moving a mob a few blocks and it would place the mob, it'd sit there with no collision, and move back to its original position.

**Comment by aaronhowser1** [comment]
Unfortunately, the only fix for this I can provide is a tooltip to the item and a line in the quest saying that this might happen.
