### ISSUE TITLE
Just an opinion on questing (Integrate recipes {magic(blood magic, botania ect) mods and other mods} that force using that mod.

### ISSUE THREAD

**Issue by jduece** [FTBTeam/FTB-University#188]
**Integrate Recipes That Make You Use Other Mods**
OK i know that title is long but i wanted my thoughts to hopefully be read in one sentence. Anyway, I believe the pack would be 1 million times better if you made it to where you had recipes that made you actually have to use a mod because as of right now while ive been playing the pack for a few days. It seems that i have no reason to get into like blood magic and botania, rats all of the mods that i would love to get into but there isnt any reason to go through them. I find it hard to get into a mod unless it actually benefits me in the recipes. Hopefully this thought gets noticed and i hope it comes to fruition.

Thank You -Jeremy

**Comment by NuclearDogs-1** [comment]
You need blood tanks for the creative tank. And the reason you want to get into rats is some minor automation. University is basically a Kitchen-Sink Pack with Creative item goals, and quests. Kitchen Sink packs usually don't modify recipes to force you to do a certain mod. I do think that there should be more recipes for Botania and Blood Magic, but the final questline has creative items from every mod with a questline, excluding I think Rats and DML.

**Comment by aaronhowser1** [comment]
You're basically asking for University to be an Expert pack, which... kind of defeats the purpose. I tried to do something similar, in Endgame and with Trophies, but I won't change *literally all recipes in all mods* to make you go through them all. That would change the genre entirely.

**Comment by jduece** [comment]
Im not saying change all the recipes just some in order to push you into a
mod and an expert pack would be considered more difficult recipes in my
opinion but im just saying make it worth your while to go through a magic
mod. Also add a mod to up the stack size of ender pearls and what not.
