### ISSUE TITLE
[Quest Problem]: IC2 - Coolant

### ISSUE THREAD

**Issue by SneakyPika** [FTBTeam/FTB-University#189]
* What version of University: 1.1.0
* What quest: You're Hot, Then You're Cold
* What is the problem: Quest description is incomplete? via???
<img width="431" alt="Screen Shot 2020-11-11 at 3 41 38 PM" src="https://user-images.githubusercontent.com/61877523/98867656-8a2c7200-2434-11eb-9d97-2a2983f474f4.png">

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/99142571-e1406b80-261b-11eb-8e24-683c7e3f35d2.png)
Fixed, thank you. I also apparently had a whole paragraph that I forgot to actually put in!
