### ISSUE TITLE
[Mod Problem]: EnderIO XP Vacuum Doesn't Output

### ISSUE THREAD

**Issue by Dooblin** [FTBTeam/FTB-University#195]
* What version of University: 1.1.1
* What mod: EnderIO
* Have you made an issue on their issue tracker: No
* If so, link it here: N/A
* Describe the issue: I have activated my XP Vacuum for my mob farm by right clicking it with the Liquid XP Bucket and it is collecting XP orbs just fine. However, I am unable to get the XP Vacuum to output. I have tried directly into the Experience Obelisk, directly into the EnderIO tank, using an Ender Fluid Conduit into the Experience Obelisk, using an Ender Fluid Conduit into the EnderIO tank, and the Pressurized tank from EnderIO, nothing seems to be working.

**Comment by aaronhowser1** [comment]
Why close #194? I don't see a difference between the two.

**Comment by Dooblin** [comment]
> Why close #194? I don't see a difference between the two.

I didn't have the correct labels and this is the first time posting so I just closed it.

**Comment by Dooblin** [comment]
The XP Vacuum does output, I thought it could collect exp through walls, but it cannot.
