### ISSUE TITLE
[Modpack Problem]: Creative Compressor Recipe doesn't work

### ISSUE THREAD

**Issue by SneakyPika** [FTBTeam/FTB-University#201]
* What version of University: 1.1.0
* Describe the issue: Recipe doesn't seems to accept air canister correctly. Maybe because air canisters have durability, all of the canisters are completely full. 
<img width="594" alt="Screen Shot 2020-11-14 at 4 01 56 PM" src="https://user-images.githubusercontent.com/61877523/99157934-0b814000-2693-11eb-9457-a3c9457c63ef.png">

**Comment by Sigmur** [comment]
Same problem in version 1.1.1
I'm trying to craft it in a packager auto crafter. I have ~20 full air canister in my AE system but it tells me that i'm missing 10, so it seems that i managed to fill 2 can and match the recipe datas. No idea how tho.

Edit : The cells from creative works, but now i have the same problem with the minigun ammo : doesn't work when crafted but work when added in creative.

**Comment by melbellrocks** [comment]
Same issue here with this recipe not working in 1.1.1

Only difference I see in my items and the recipe items are the aforementioned durability NBT on the air canisters.

EDIT:  I am crafting manually, not with the autocrafting.

**Comment by melbellrocks** [comment]
ok i have confirmation that the creative air compressor not crafting is due to the reinforced air canisters.  When I fill the tanks manually the recipes doesn't work (full to 20 bar pressure), but when i spawn in full canisters from creative, the recipe works

**Comment by aaronhowser1** [comment]
The recipe is already changed for 1.2 entirely
