### ISSUE TITLE
[Mod Problem]: Warp Controller not showing planets

### ISSUE THREAD

**Issue by robertstepp** [FTBTeam/FTB-University#204]
* What version of University: 1.1.0 and 1.1.1
* What mod: Advanced Rocketry
* Have you made an issue on their issue tracker: No
* If so, link it here: 
* Describe the issue: When accessing the Warp Controller on a space station, no planets show up. I have tested in 1.1.0 and 1.1.1 in single player and on a server. While in a single-player game, I can see all of the planets in the Warp Controller but not on a server running the same save as the single-player game. But if I use the Holographic Planet Selector, I can see all planets in the Sol and Gimmick Galaxies then warp to them. It might be a sync issue with the Warp Controller and not getting information from the server. I can provide server and client logs if needed.

This may be the same thing as [https://github.com/FTBTeam/FTB-University/issues/58](https://github.com/FTBTeam/FTB-University/issues/58)

**Comment by SneakyPika** [comment]
this is a dup of #202 there is a temporary fix there.
