### ISSUE TITLE
Bad Item naming

### ISSUE THREAD

**Issue by EReeeN1208** [FTBTeam/FTB-University#208]
The Item, "S'more S'mingot Singularity" should be changed to "S'more S'mingularity"

I hope you change the name as it would be a wasted opportunity

**Comment by aaronhowser1** [comment]
I wanted to do this but I can't. The name is dynamic, the only thing I can change is everything before Singularity. I also tried using CT, but it didn't work. You have no idea the disappointment I felt when I realized it wasn't possible.
