### ISSUE TITLE
[Quest Problem]: Void Ore Controller sometimes has NBT data

### ISSUE THREAD

**Issue by Raidobw2** [FTBTeam/FTB-University#209]
FTB Discord Original Post Link: https://discord.com/channels/372448486723158016/767004467974504448/778383048843853835

* What version of University: 1.1.1
* What quest: The Void Ore Miner 2 Quest (and all other controllers quests i assume)
* What is the problem:

The quest `7747cbec`, or ftbuniversity.voidore2 in the Environmental Tech tab, does not complete if you have a Controller that has been placed beforehand. The Controller gets owner data (NBT) if placed and upon pickup does not get recognized in the quest for completion.
This is the quest data, taken from the snbt config file:
```
{
    title: "{ftbuniversity.voidore2.title}",
    x: 4.0d,
    y: 0.0d,
    description: "{ftbuniversity.voidore2.subtitle}",
    text: [
        "{ftbuniversity.voidore2.desc}",
        "",
        "{ftbuniversity.etechmodifiers}",
        "",
        "{ftbuniversity.etechreadguide}"
    ],
    dependencies: [
        "b7509d9b"
    ],
    tasks: [{
        uid: "bba40d5b",
        type: "item",
        items: [{
            item: "environmentaltech:void_ore_miner_cont_2"
        }]
    }]
}
```
Since all quests from this chapter follow a pattern, i'm guessing all quests that require a Controller of some type in Environmental Tech Quests could potentially have this problem.

Kindly,

Antoine

**Comment by aaronhowser1** [comment]
Set all quests in ETech chapter to ignore NBT
