### ISSUE TITLE
Bug when sleep

### ISSUE THREAD

**Issue by Tomas1599** [FTBTeam/FTB-University#21]
When i sleep nearby a wall, i take damage util i die, please see that bug and try solve him

**Comment by ghost** [comment]
So I encountered this as well and did a bit of testing. I was able to place my bed against a normal wall and sleep fine, but when a bed is placed directly in front of—or—on a block adjacent to a rat hole from the Rats mod.

**Comment by aaronhowser1** [comment]
Somnia was removed so hopefully this is resolved
