### ISSUE TITLE
[Quest Problem]: Several quests don't ignore NBT when they should

### ISSUE THREAD

**Issue by NuclearDogs-1** [FTBTeam/FTB-University#215]
* What version of University: 1.1.1
* What quest: Environmental Tech Multiblock machines quests, Mechanical/Normal Squeezer Quests, Mechanical/Normal Drying Basin Quests, There probably are more, I just haven't found them
* What is the problem: FTB Quests can be a little slow in detecting quest items. So, it allows you to put the quest item down before it detects it. Sometimes, you may also obtain a quest item before you unlock the quest. Some blocks retain NBT when picked up, leading to the Quest not being able to read the blocks because it doesn't ignore NBT.

**Comment by aaronhowser1** [comment]
Set those quests to ignore NBT
