### ISSUE TITLE
[Crash]: Using Clippers on some crops crashes the game.

### ISSUE THREAD

**Issue by new-3** [FTBTeam/FTB-University#22]
* What version of University: 1.0.0
* Have you added any mods: No

* Crash report link (preferably Pastebin etc, not the file): https://pastebin.pl/view/35730c6a

* What were you doing when the crash happened: After using a Clipper(from Agricraft mod) on some crops(ex. pumpkin, beetroot) growing in the crop stick, the game crashes and world become unplayable.

* Any other details: In this case I used red seed.

**Comment by aaronhowser1** [comment]
InfinityRaider/InfinityLib/issues/32

**Comment by FestplattenSchnitzel** [comment]
Can confirm this.

- What version of University: 1.1.1
- Environment: Multiplayer
- Have you added any mods: No
- What were you doing when the crash happened: Using clipper on crop (first crash) **and** trying to rejoin the server (second crash)
- Any other details: I used Crystalline seed.

Edit:
This seems to be a client side issue; it works flawless, if I restart the client and then join the server again.

Happened on freshly cultured crop.

**Comment by aaronhowser1** [comment]
Agricraft is being removed in 1.2
