### ISSUE TITLE
JEI cleanup of nether quartz dusts

### ISSUE THREAD

**Issue by Miisi** [FTBTeam/FTB-University#221]
Currently there's four types of nether quartz dust present in JEI:

- Quartz Powder (from EnderIO)
- Nether Quartz Dust (from AE2)
- Powdered Quartz (from Mahou Tsukai)
- Crushed Quartz (from NC)

The intended one to use seems to be NC's, considering the large amount of ways to obtain it.

**Comment by AggressiveChairs** [comment]
In addition, you can't make any of the dusts in IC2's macerator.

**Comment by aaronhowser1** [comment]
Removed:
* Tin Powder
* Copper Powder
* Coal Powder
* Gold Powder
* Obsidian Powder
* Lapis Lazuli Powder
* Quartz Powder
* Coal Dust
* Crushed Obsidian
* Crushed Coal
* Obsidian Dust
* Ender Pearl Dust
* Obsidian Dust

all of which are duplicates of other stuff
