### ISSUE TITLE
[Mod Problem]: Extra Utilities 2 Golden Lasso Error

### ISSUE THREAD

**Issue by AntEncarnacion** [FTBTeam/FTB-University#224]
* What version of University: v1.1.1
* What mod: Extra Utilities 2
* Have you made an issue on their issue tracker: No
* If so, link it here: N/A
* Describe the issue: Whenever I try to place a captured mob with the golden lasso the mob simply disappears.

**Comment by NuclearDogs-1** [comment]
It is in the quest description for the golden lasso. READ THE QUEST.

**Comment by aaronhowser1** [comment]
It's also in in the tool tip for the item
