### ISSUE TITLE
[Crash]:  Another set of crashes, seems to be happening over and over. 

### ISSUE THREAD

**Issue by Jinxy2004** [FTBTeam/FTB-University#229]
* What version of University: 1.1.1
* Crash report link (preferably Pastebin etc, not the file): https://pastebin.com/wdk0fBeG
* What were you doing when the crash happened: I was sitting in my rftools dimension with the time dimlet.
* Any other details: This is not the same as the other post.

**Comment by aaronhowser1** [comment]
```
    at svenhjol.charm.world.feature.SpectreHaunting.onTick(SpectreHaunting.java:107)
```
Known issue, disable SpectreHaunting in the Charm config. #165 #75
