### ISSUE TITLE
[Quest Problem]: In Advanced Rocketry we cant seem to get to the Origin Planet via vanilla methods

### ISSUE THREAD

**Issue by epicepicgrolith** [FTBTeam/FTB-University#234]
* What version of University: 1.1.0
* What quest: Advanced Rocketry 
* What is the problem: The quest implies going to this crazy rich planet but we cant seem to get there in multiplayer. This would also tie-in to the problem other people are having using the warp core in Advanced Rocketry. I also what to know if we are intended to get there because late game infinity blocks natural generate there. 

Thank you

**Comment by aaronhowser1** [comment]
Is this not the same issue as #202? I'll reopen if not, but try putting the artifact into the artifact slot in the warp core, then using the hologram thing to get there.
