### ISSUE TITLE
Menu - Controls - off to the left

### ISSUE THREAD

**Issue by MikaelS111** [FTBTeam/FTB-University#235]
FTB University: 1.1.1.

Never seen this before in any modpacks. When I go into the Menu -> Controls, all control info are off to the left.

I've tried with fullscreen on and off, same experience.

![menu](https://user-images.githubusercontent.com/15056341/100551614-11c20f80-3282-11eb-8f4f-6211530aa46f.JPG)

**Comment by aaronhowser1** [comment]
This is because one of the controls' name is super long, and for some reason Minecraft pushes all others to the side. Set your GUI scale lower
