### ISSUE TITLE
[Crash]: "Internal Server Error" when loading RFTools dimension

### ISSUE THREAD

**Issue by naptimeshadows** [FTBTeam/FTB-University#239]
* What version of University: 1.1.1
* Have you added any mods: No
* If yes, which mods:
* Crash report link (preferably Pastebin etc, not the file): https://pastebin.pl/view/ba1e25b6
* What were you doing when the crash happened: Loading any RFTools dimension. Not even using any modifiers or trying to force anything.
* Any other details:

**Comment by Misza13** [comment]
Can confirm same issue, crash report: https://pastebin.pl/view/4eeefa0d

Keeps crashing after a few seconds when I try to reopen the world. Any ideas how I can move myself out of the dimension?

**Comment by naptimeshadows** [comment]
> Can confirm same issue, crash report: https://pastebin.pl/view/4eeefa0d
> 
> Keeps crashing after a few seconds when I try to reopen the world. Any ideas how I can move myself out of the dimension?

I know you can get an editor to change your NBT player file and change your location. It's easiest just to set to overworld 0, 70, 0 and just drop at worldspawn.

**Comment by Iris-xii** [comment]
I came here to report this too, but I think it's the same issue as #165 , and you can probably fix it by editing charm.cfg to disable SpectreHaunting. It's worked for me, at least!
