### ISSUE TITLE
[Crash]: Server tick took 60 seconds, possibly due to ic2

### ISSUE THREAD

**Issue by Pop115** [FTBTeam/FTB-University#252]
* What version of University: 1.1.0
* Have you added any mods: no
* Crash report link (preferably Pastebin etc, not the file): https://pastebin.com/LZkC4R1H
* What were you doing when the crash happened: Happened multiple times, doing different things, just killing mobs, changing dimensions

My server is on FTB University 1.1.0 as the 1.1.1 is not yet available on my hosting service, the server crashed multiple times and the logs show a lot of ic2 messages. Is this a known problem with ic2? 

I could try updating to 1.1.1 but the patch note only show that OTG was fixed, are there other changes brought with 1.1.1. that could help me?

**Comment by Pop115** [comment]
Looks like it work with 1.1.1, the message for the update on the ftb website "Fixed OTG Core mismatch when updating existing instances" should probably also say that it fixes this server tick problem.

**Comment by aaronhowser1** [comment]
If not, just delete the file `/mods/1.12.2/otgcore.jar`
