### ISSUE TITLE
[Crash]: Optifine 1.12.2

### ISSUE THREAD

**Issue by m1dn1ck** [FTBTeam/FTB-University#255]
* What version of University:1.1.1
* Have you added any mods: Yes
* If yes, which mods: optifine 1.12.2
* Crash report link (preferably Pastebin etc, not the file): https://pastebin.com/cydhSP1v
* What were you doing when the crash happened: starting with optifine
* Any other details:

**Comment by aaronhowser1** [comment]
Optifine is unsupported
