### ISSUE TITLE
[Modpack Problem]: Recipe Conflicts: Logs for chests, Logs for Bark

### ISSUE THREAD

**Issue by TeetoKaziim** [FTBTeam/FTB-University#26]
* What version of University: 1.0.0
* Describe the issue: 
* **First:**
Recipe: extrautils2:shortcut_chest (8 of any logs in a ring craft into 4 vanilla chests) conflicts with and prevents the use of Quark's log-based recipes for its alternate wood chests. (Each of which has a recipe for 8 specific logs in a ring to craft into that specific chest type)

Suggested solution: Quark itself has a 8 oak logs become Vanilla Chest recipe, so the extra utils recipe can be pretty safely removed.

* **Second:**
Recipe for Prefab Mod's Bundle Of Timber conflicts with and prevents the crafting of Quark's Bark blocks.

Suggested solution: Forestry's Wood Piles already occupy the "2x2 of logs" recipe, perhaps changing the Quark Bark to give you 6 blocks for 6 logs?

**Temporary Workaround for any users who are desperate:**
Forestry's worktable allows toggling between conflicting outputs for recipes.

**Comment by aaronhowser1** [comment]
Fixed by removing `extrautils2:shortcut_chest` and changing the Prefab recipe to require String on top and bottom centers

**Comment by TeetoKaziim** [comment]
The uh, Bundle Of Timber uncrafts into 9 oak logs.

I don't know if you care about enabling the player to convert string into logs, but might wanna change that to 7, for that fix, since you're reducing the log cost, this is like, the silliest nitpick, but, uh, here we are!

**Comment by aaronhowser1** [comment]
Lol good point, fixed that too
