### ISSUE TITLE
[Mod Problem]: Forestry Engines Not Dropping Block When Broken

### ISSUE THREAD

**Issue by JanGamm** [FTBTeam/FTB-University#268]
* What version of University: 1.2.1
* What mod: Forestry
* Have you made an issue on their issue tracker: No
* If so, link it here: 
* Describe the issue: When breaking Forestry's engines (Peat-fired, Biogas, Clockwork, or Electrical) with any tool, the block does not drop.

**Comment by aaronhowser1** [comment]
Duplicate of #52
