### ISSUE TITLE
[Modpack Problem]: Creative quests fire for regular versions of certain items

### ISSUE THREAD

**Issue by quat1024** [FTBTeam/FTB-University#27]
FTB University 1.0.0

* Crafting a Basic Gas Tank from Mekanism awards the Endgame - Creative Gas Tank quest.
* Crafting a mana tablet from Botania awards the Endgame - Creative Mana Tablet quest.
* Idk maybe there's more

**Comment by quat1024** [comment]
This does *not* happen for the mana *pool* quest, btw, so it's not *inherent* to quests with items that differentiate between survival and creative versions with merely an NBT tag. I'm not familiar with how ftb quests works but you might need to tighten up a few item matching restrictions

**Comment by aaronhowser1** [comment]
It's definitely an NBT problem, I probably forgot to set them to not ignore NBT.
