### ISSUE TITLE
[Crash]: Even failed to open my world

### ISSUE THREAD

**Issue by Mkfb2002** [FTBTeam/FTB-University#270]
* What version of University: 1.2.1
* Have you added any mods: No
* If yes, which mods: -
* the error link does not show
* What were you doing when the crash happened: Loading my world 
* Any other details: It says that the mod: Open terrain generator might have caused this. Also I followed a previous thread that said to delete the dynamic surroundings file and it didn't work.
* 
![Screenshot 2021-01-15 193933](https://user-images.githubusercontent.com/77502153/104753791-876a3800-5769-11eb-80de-24d03069b337.png)

**Comment by aaronhowser1** [comment]
Read the changelog.

**Comment by Mkfb2002** [comment]
thanks
