### ISSUE TITLE
[Mod Problem]: Create Encased Chain Drives occasionally create their own rotation

### ISSUE THREAD

**Issue by 923penguin** [FTBTeam/FTB-University#272]
* What version of University: 1.4.1
* What mod: Create
* Have you made an issue on their issue tracker: No
* If so, link it here: 
* Describe the issue: Occasionally, when creating systems using Create, random encased chain drives will turn on their own, and continue to convey their own rotation through the system. This causes a lot of problems with altering the system because new parts will just pop off, and rotational speed controllers will be unusable until the affected chain drive is broken and replaced.

**Comment by aaronhowser1** [comment]
FTB University is for Minecraft 1.12, and does not have Create in it. University doesn't even *have* a 1.4.1 version yet. I don't think you're on the right issue tracker.
