### ISSUE TITLE
[Modpack Problem]: Charged certus quartz is too rare

### ISSUE THREAD

**Issue by Discusser** [FTBTeam/FTB-University#28]
* What version of University: 1.0.0
* Describe the issue: Charged Certus Quartz Ore is extremely rare.

After mining for quite a while, I find it weird how I've gotten more diamonds than charged certus quartz ore, even though in my previous modpacks when looking in the same areas I found decent amounts of it. I decided to check JEI to see how rare charged certus quartz is on earth and I saw spawn rates of less than 0.01%, in comparison to diamonds which is 0.13%.

**Comment by aaronhowser1** [comment]
Apparently Certus Quartz Ore has a 8% chance of being Charged. Upgraded to 16%.

**Comment by random51** [comment]
You only need enough to get to where you can charge your own, if anybody is worried about this slowing them down. Additionally you get plenty from an ETech void ore miner.
