### ISSUE TITLE
[Mod Problem]: Breaking Forestry Engines doesn't give you an mini version to put in inventory

### ISSUE THREAD

**Issue by lolina051586** [FTBTeam/FTB-University#288]
* What version of University: 1.2.1
* What mod: Forestry
* Have you made an issue on their issue tracker:
* If so, link it here: 
* Describe the issue: When I place down a any engine from the Forestry Mod and then break it with any pickaxe so that I can place it some where else, after breaking it, the mini version doesn't spawn to be picked up and then I get an error message saying something has gone wrong.

**Comment by aaronhowser1** [comment]
Duplicate of #52
