### ISSUE TITLE
[Mod Request]: swing through grass

### ISSUE THREAD

**Issue by daitanfutekina** [FTBTeam/FTB-University#294]
* Mod Name: swing through grass
* Mod Dependencies: n/a
* Mod License: mit
* Mod Link:https://www.curseforge.com/minecraft/mc-mods/swingthroughgrass
* Why you want it: its important and it fixes a problem

**Comment by aaronhowser1** [comment]
Isn't this already in?

**Comment by daitanfutekina** [comment]
> Isn't this already in?

yeah thats why I closed it, I had it turned off temporarily
