### ISSUE TITLE
[Mod Problem]: Remove Thaumcraft

### ISSUE THREAD

**Issue by Legomonster33** [FTBTeam/FTB-University#295]
* What version of University: 1.2.1
* What mod: Thaumcraft
* Have you made an issue on their issue tracker: no
* If so, link it here: no
* Describe the issue: At not point is it fun or useful, please remove garbage mod from the pack.

**Comment by daitanfutekina** [comment]
isn't thaumcraft a popular mod? the point of ftb university is to teach complicated popular mods

**Comment by aaronhowser1** [comment]
No. Just because you're unable to read the book and quests that say how to avoid problems doesn't make it the mods fault that you get taint, nor does it make the mod "garbage".
