### ISSUE TITLE
[Modpack Problem]: Extremely aggressive hostile mobs that see through walls

### ISSUE THREAD

**Issue by LimiChan** [FTBTeam/FTB-University#30]
* What version of University: 1.0.0
* Describe the issue:  
- To say it simply. Mobs are spawning left and right and can instantly detect you even when you're far away or out of their line of sight, and no, that's not only Zombies.
- also to add onto that, they only target a singular person unless that person is really far away, even when the mobs get attacked by each other or other players.

![2020-10-20_12 54 57](https://user-images.githubusercontent.com/73175721/96587003-0cb48c80-12e2-11eb-81d9-7a3d7173b1f4.png)

**Comment by siktro** [comment]
Also ran into this mobs behavior. Toggled varios mods and it seems turning off "Genetics Reborn" worked for me.
Most basic check is to try to spawn spider via spawn egg at daytime. At vanilla behavior spider will not attack player. With "Genetics Reborn" spider will immediately attack.
Tbh i don't know is it intended behavior or not.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/97039243-b89fe700-1531-11eb-9455-71d2444ac6f7.png)

![image](https://user-images.githubusercontent.com/15698722/97039254-bccc0480-1531-11eb-87b7-36a88446c238.png)

And then after removing GR
![image](https://user-images.githubusercontent.com/15698722/97039915-d457bd00-1532-11eb-84c9-2d6fd09e57f8.png)

Very very unfortunate, but I guess it has to go until fixed :(

**Comment by soupcant95** [comment]
damn, a friend of mine could've used that mod. oh well, better than having very angry mobs

**Comment by aaronhowser1** [comment]
TheUnderTaker11/GeneticsReborn/pull/217

Good news!
