### ISSUE TITLE
IC2 Sounds Bar in UI is misplaced. Just a formatting issue.

### ISSUE THREAD

**Issue by Knilore** [FTBTeam/FTB-University#316]
![2021-04-28_08 48 54](https://user-images.githubusercontent.com/83355342/116418456-c5afd280-a801-11eb-8c80-b9f52b919c94.png)

I'm new to GitHub so hopefully my Screenshot loads, but in the Sounds Menu the IC2 slider is half a position higher than it should be.

**Comment by aaronhowser1** [comment]
Nothing I can do about this, that's on IC2 and it hasn't been updated in forever

**Comment by Knilore** [comment]
Cool. I decided to opt into analytics on this pack and thought I'd try to
figure out the issue tracker with something I noticed that wasn't complex
and I didn't find it already posted. Thanks for letting me know.
