### ISSUE TITLE
Gendustry Exception on loading

### ISSUE THREAD

**Issue by KamuiKat** [FTBTeam/FTB-University#323]
Friend of mine is trying to join my University server but can't even start the game as it stops during the mod loading process and has tried reinstalling and increasing ram with little luck.

He gave me the actual crash logs, provided [here.](https://paste.dimdev.org/uzopacepib.mccrash)

**Comment by aaronhowser1** [comment]
Have him uninstall the pack, restart his pc, and reinstall it. From this: 
```
Caused by: java.lang.NoClassDefFoundError: net/bdew/lib/recipes/RecipeParser
```
looks like he possibly has a corrupted download
