### ISSUE TITLE
[Modpack Problem]: client crash while working with rftools storage scanner

### ISSUE THREAD

**Issue by natebc** [FTBTeam/FTB-University#37]
* What version of University: 1.0.0
* Describe the issue: closing out of rftools scanner and the client crashed.

crash-report: https://gist.github.com/natebc/49a3d12688b7e9263f226f1d98f1df74

**Comment by aaronhowser1** [comment]
This is a mod problem, not modpack. Can you also report this to the [RFTools issue tracker](https://github.com/McJtyMods/RFTools/issues)? Copy/paste `FTBTeam/FTB-University/issues/37` anywhere in the issue, so it'll link it to this one.

**Comment by natebc** [comment]
Reported to mod tracker, McJty is no longer developing on 1.12.2 but took a look at this crash report and cannot reproduce the crash so we'll have to hope this is a rare thing. Hopefully only me!
