### ISSUE TITLE
[Modpack Problem]: No Immortaility when you teleport to Dimension 

### ISSUE THREAD

**Issue by FoxesEyes** [FTBTeam/FTB-University#4]
* What version of University:1.0
* Describe the issue: I done the first 2000steps, chose Vanilla Vistas Amplified, didn't get Resistance, died 700m away.

**Comment by aaronhowser1** [comment]
Figured out the issue, I accidentally used `@player` instead of `@p` in the command reward. That's a bit embarrassing 😅
