### ISSUE TITLE
[Quest Problem]: Agricraft Botania seeds cannot be crafted

### ISSUE THREAD

**Issue by Tedris** [FTBTeam/FTB-University#41]
* What version of University: 1.0.0
* What quest: Botania Seeds
* What is the problem: Cyan, Gray, Yellow, White botania seeds do not have recipes so this quest cannot be started.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/96769481-d0963000-13a4-11eb-90cb-59b4a5062c82.png)
![image](https://user-images.githubusercontent.com/15698722/96769503-d68c1100-13a4-11eb-90d0-3565df624b0d.png)
![image](https://user-images.githubusercontent.com/15698722/96769526-dd1a8880-13a4-11eb-8105-3fdf005e77f1.png)
![image](https://user-images.githubusercontent.com/15698722/96769535-e0ae0f80-13a4-11eb-82a4-aa76c11eab2e.png)
fixed
