### ISSUE TITLE
[Crash]: Crafting Station causes crash with Barrel

### ISSUE THREAD

**Issue by EReeeN1208** [FTBTeam/FTB-University#42]
What version of University: 1.0
Have you added any mods: no
If yes, which mods: no
Crash report link (preferably Pastebin etc, not the file): I sent the whole folder so you can see 120 of them (: https://drive.google.com/file/d/11-HzPyIyJQXXQMB7-scIfaCOED1Sinkf/view?usp=sharing     
The latest one: https://pastebin.pl/view/6fea4797
What were you doing when the crash happened: I opened a crafting station
Any other details: there was an  "item barrel" (from yabba)  with lots of cobble in it (42x64) and it gives me this error covering up half my screen and its very annoying while crafting

**Comment by aaronhowser1** [comment]
Send only the crash report that's important (the most recent one)
