### ISSUE TITLE
[Mod Problem]: Breaking a Forestry block causes an error message

### ISSUE THREAD

**Issue by Blythus** [FTBTeam/FTB-University#45]
Breaking a block from the Forestry mod causes an error message to pop up and does not drop the broken block.

I added Optifine and removed Dynamic Surroundings and Fancy Block Particles from my pack.

[crash-2020-10-21_16.47.13-server.txt](https://github.com/FTBTeam/FTB-University/files/5418859/crash-2020-10-21_16.47.13-server.txt)

**Comment by aaronhowser1** [comment]
Why close this?

**Comment by Blythus** [comment]
Oh, I messed up the templating. I was going to gather more info about it and resubmit.
