### ISSUE TITLE
[Mod Request]: Architect

### ISSUE THREAD

**Issue by OneLemonyBoi** [FTBTeam/FTB-University#46]
* Mod Name: Architect
* Mod Dependencies: None
* Mod License: MIT
* Mod Link: [Here](https://www.curseforge.com/minecraft/mc-mods/architect)
* Why you want it: It's one of the only "prebuilt" mods that can properly handle Tile Entities, according to its CurseForge page. A starter reactor can be provided to players in the beginning of NCO, giving the player a helping hand. However, it doesn't provide the blocks. That means that the player has to still put in effort. If you want the blueprint to be one-use, then just add [this mod.](https://www.curseforge.com/minecraft/mc-mods/jj-fix-architect)

**Comment by aaronhowser1** [comment]
I could also use this for certain other structures, like the Mekanism Reactor! Very useful.

**Comment by aaronhowser1** [comment]
Looks like it can't do tile entities, at least the 1.12 version. That's basically the only thing I wanted it for.

**Comment by OneLemonyBoi** [comment]
It seems that you have to define the tile entities that can be copied in the whitelist.json generated by the mod, and set value types for each nbt data tag. [The GitHub page](https://github.com/MightyPirates/Architect) for Architect states that it must be a whitelist, not a blacklist. [This video](https://youtu.be/I-T90MsfTy4?t=692) by the creator of the modpack shows how allowing tile entities work.

**Comment by OneLemonyBoi** [comment]
Luckily you don't have to restart Minecraft in order to view the changes, and it should do most of the work for you.

**Comment by OneLemonyBoi** [comment]
[Link to quick tutorial](streamable.com/fcih1d)

**Comment by OneLemonyBoi** [comment]
And it retains nbt, tested it

**Comment by aaronhowser1** [comment]
Can't get it to use metadata, but otherwise is good enough to include
