### ISSUE TITLE
[Mod Request] Draconic Evolution

### ISSUE THREAD

**Issue by NuclearDogs-1** [FTBTeam/FTB-University#48]
* Mod Name: Draconic Evolution
* Mod Dependencies: Brandon's Core, Redstone Flux, Project Intelligence 
* Mod License: "Don't Be a Jerk" License created by CoFH
* Mod Link: https://www.curseforge.com/minecraft/mc-mods/draconic-evolution
* Why you want it: I feel like I can learn a lot about this mod and it is an advanced mod that could have a long series of quests. Additionally, it is in quite a few packs. I was originally going to suggest GregTech: Community Edition, but that seemed a bit much, and it would mess with the IC2 quests. If there is some way you could implement GT:CE, I would really appreciate it.

**Comment by aaronhowser1** [comment]
Draconic was in Academy, so it doesn't really need to be taught. I also
just generally dislike the mod, and feel it would be mildly redundant in
this pack.
