### ISSUE TITLE
[Modpack Problem]: 

### ISSUE THREAD

**Issue by Discusser** [FTBTeam/FTB-University#5]
* What version of University: 1.0.0
* Describe the issue: First quest tells you to walk 100 blocks, but in the lore it says "xxxx/10000" instead of "xxx/100". Though 1 block counts as 100 blocks. 
![image](https://user-images.githubusercontent.com/47938380/96347512-caedd100-10aa-11eb-835e-fcfd652a2de7.png)

**Comment by aaronhowser1** [comment]
So what's the problem? 100 units is one block. 10000 units is 100 blocks.

**Comment by Discusser** [comment]
Well it makes people think it's 10000 blocks and not 10000 units.

**Comment by aaronhowser1** [comment]
No, it says 100 blocks like six times in the quest. Did you think that, at the time you took that screenshot, you'd already walked **640** blocks?
