### ISSUE TITLE
[Mod Problem]: 

### ISSUE THREAD

**Issue by AAAAAHONDAAAAA** [FTBTeam/FTB-University#50]
* What version of University: 1.0
* What mod: Ender IO & Quark
* Have you made an issue on their issue tracker: No
* If so, link it here: 
* Describe the issue: I tried applying an Ancient Tome to my Ender, but it wouldn't work. It didn't give me anything besides the fact I couldn't do it. I've tried this with regular enchanted books, and it has worked just fine. Is there any way for the pack to remove the conflict between these mods?

**Comment by aaronhowser1** [comment]
You're using Tomes wrong. You combine the Tome with a Book, then that upgrades the Book, which you combine with the Sword.
