### ISSUE TITLE
[Mod Problem]: NCO Ores with Mek Enrichment Chamber

### ISSUE THREAD

**Issue by ThePoleThatFishes** [FTBTeam/FTB-University#56]
* What version of University: 1.0.0
* What mod: NC: Overhaul + Mekanism
* Have you made an issue on their issue tracker: No, it's a recipe issue
* If so, link it here: -
* Describe the issue: Mek Enrichment Chamber can only process NCO Uranium ore and not the other ores (Thorium, Magnesium, Boron and Lithium). Please add recipes for these ores too! :D

**Comment by aaronhowser1** [comment]
Added JAOPCA, should fix
