### ISSUE TITLE
[Quest Problem]: Kikoku Quest confusing text

### ISSUE THREAD

**Issue by Chik3r** [FTBTeam/FTB-University#6]
* What version of University: V1.0.0
* What quest: `All According to Kikoku`
* What is the problem: The void damage part is confusing, it says `It also does void damage, which functions like void damage ...`
![image](https://user-images.githubusercontent.com/31808958/96350209-07113980-108b-11eb-9a19-874d4afc9e7c.png)

**Comment by OneLemonyBoi** [comment]
I'm pretty sure the first void damage refers to void being the type of damage, and the 2nd one being void damage, as in falling into the void. However, it could be worded better.

**Comment by aaronhowser1** [comment]
Meant to say Divine damage, lol
