### ISSUE TITLE
Unable to exit Chat after Sleeping

### ISSUE THREAD

**Issue by Crystallyne** [FTBTeam/FTB-University#61]
I took refuge in a cave when night fell, and put my bed up against 2 walls (in a corner). After sleeping through the night, and appearing to exit my bed, I ended up with a screen where my chat window was open, the "Leave Bed" button was still up, but I couldn't do anything. The screen DID change when I initially got out of bed, so the screen you see in the screenshot below is not the  same as what I saw when I was actually in bed.

Hitting escape did nothing, and clicking "Leave Bed" repeatedly did nothing. I literally couldn't do anything else except hit Alt+F4 to force the game closed. (Also I shouldn't have had any fatigue, but the screenshot shows I still had fatigue...)

![2020-10-23_07 41 20](https://user-images.githubusercontent.com/32418385/97018342-e66e3700-1503-11eb-8ae7-04195e1dac04.png)

**Comment by NuclearDogs-1** [comment]
The Sleeping mod is going to be gone in 1.1.0, so you shouldn't run into this issue once you update the pack.
