### ISSUE TITLE
[Modpack Problem]: Nether Star Generation (Broken Power Supply)

### ISSUE THREAD

**Issue by Montey300** [FTBTeam/FTB-University#65]
* What version of University: 1.0.0
* Describe the issue: Its not an "issue" but it's easily abusable, and might even break "progression", you can easily automate nether stars, and end up generating 9 million RF total every 2 minutes. Could easily rush other stuff with said power supply, and might "negate" the use of other sources.

**Comment by aaronhowser1** [comment]
Removed the DML recipe for nether stars, won't change the RF gen unless another super-easy way to get stars is found
