### ISSUE TITLE
[Crash]: Minecraft is crashing when I open my inventory

### ISSUE THREAD

**Issue by Hanashima2** [FTBTeam/FTB-University#73]
* What version of University: 1.0.0
* Have you added any mods: -
* If yes, which mods: -
* Crash report link (preferably Pastebin etc, not the file): https://pastebin.com/Xtm8WSeL
* What were you doing when the crash happened: I just opened my inventory and it crashed. And it keeps crashing when I try to open my inventory

* Any other details: I changed the Agricraft config for netherquartz  but this was a week ago

**Comment by aaronhowser1** [comment]
Why close?

**Comment by aaronhowser1** [comment]
Does this persist if you remove AgriCraft?

**Comment by Hanashima2** [comment]
I fixed the problem by taking out my resource pack.

**Comment by aaronhowser1** [comment]
Agricraft is being removed in 1.2
