### ISSUE TITLE
[Modpack Problem]: Nether unavailable outside dimension 0

### ISSUE THREAD

**Issue by moon-st0ne** [FTBTeam/FTB-University#74]
* What version of University: 1.0.0
* Describe the issue: After teleporting to a different terrain style world, Nether portals cannot be lit, presumably because they only function in dimension 0. I chose the RTG + BOP version.

![image](https://user-images.githubusercontent.com/29065768/97097958-6ea82580-1645-11eb-9ce7-4656b023576b.png)

**Comment by aaronhowser1** [comment]
This is literally already mentioned in the quest. The command rewards are also being replaced with portals, so you can easily get back to the overworld.
