### ISSUE TITLE
[Mod Problem]: 

### ISSUE THREAD

**Issue by moon-st0ne** [FTBTeam/FTB-University#76]
* What version of University: 1.0.0
* What mod: MineTogether
* Have you made an issue on their issue tracker: No
* If so, link it here: 
* Describe the issue: In this pack, every player in the MineTogether chat has a purple name, as if they are playing the same pack as you. Other players in other FTB packs do not have the same issue. Other players in FTB University seem to also see everyone as purple.

**Comment by aaronhowser1** [comment]
Already fixed in next version
