### ISSUE TITLE
[Crash]: Windows BSOD

### ISSUE THREAD

**Issue by EReeeN1208** [FTBTeam/FTB-University#78]
* What version of University: 1.0
* Have you added any mods: No
* If yes, which mods: No
* Crash report link (preferably Pastebin etc, not the file): So I got 2 diffrent crash files. Im not 100% sure that these are the ones from the crash but they might be so Ive attached the latest ones. https://pastebin.pl/view/27a19cee https://pastebin.pl/view/12ca4f6e (They have been generated at the same time)
* What were you doing when the crash happened: Just playing on the server I hosted on my pc with my friends
* Any other details: It seems not to happen when Im playing alone. I remember getting 2 bsod error codes. Something about watchdog violation and kmode. Would appreciate solutions (:

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/97117345-11f24c80-16d1-11eb-880c-856c0053fad4.png)
Reinstall the pack. If it's causing a BSOD, I think that's really more your computer being messed the hell up

**Comment by redgoblin88** [comment]
note that they have said they have mixed mek cabling (basic, advanced, elite, ultimate?) andl also they use immersive cables for single machines and mek cables for bulk, so with this new info, im unsure how to replicate their setup, initially as you showed aaron, i only knew of the info that they used immersive cables and mek energy (the crashlogs indicate its primarily meks issue though)

**Comment by EReeeN1208** [comment]
I can send a world download

**Comment by EReeeN1208** [comment]
> ![image](https://user-images.githubusercontent.com/15698722/97117345-11f24c80-16d1-11eb-880c-856c0053fad4.png)
> Reinstall the pack. If it's causing a BSOD, I think that's really more your computer being messed the hell up

you think If I used a linux vm? It could work? Im going to give it a try

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/97119945-ab295f00-16e1-11eb-8c9e-343de4c947a3.png)
so someone else is getting BSODs too, but not with Mekanism

**Comment by Hanashima2** [comment]
Since I have the same problem but only with agricraft, I think that my crash log might help.

https://pastebin.com/fLfKWTpF

**Comment by Hanashima2** [comment]
> Since I have the same problem but only with agricraft, I think that my crash log might help.
> 
> https://pastebin.com/fLfKWTpF

I mean the problem gets fixed if I remove the mod but I don't want to lose all my progress.

**Comment by aaronhowser1** [comment]
Agricraft is being removed in 1.2
