### ISSUE TITLE
[Modpack Problem]: Extreamly expensive creative barrel recipe due to requiring tier 16 blood tank

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-University#81]
* What version of University: 1.0.0
* Describe the issue: The creative drum requires a tier 16 blood tank, which requires 2 tier 15 blood tanks, which requires 2 tier 14 blood tanks, which requires 2 tier 13 blood tanks, and at the end of this road, you end up with an insane amount of blank slates sense each tier costs 10 blank slates to make.

**Comment by aaronhowser1** [comment]
Changed to need tier 8
