### ISSUE TITLE
Nether portal not opening (FTB University)

### ISSUE THREAD

**Issue by AwesomeTuba682** [FTBTeam/FTB-University#82]
I've played on my world for about a week and decided I want to go to the nether, I tried making a portal to go and it wouldn't light, then I decided to check jei for any nether cake or any other ways to enter the nether, nothing. Then I checked the quests just to make sure you can and nothing was found too. The portal is fully made of obsidian (normal size 2x3) and it just won't light. Y level about 72.

**Comment by aaronhowser1** [comment]
Read the quests. You cannot make nether portals in OTG dimensions.
