### ISSUE TITLE
[Quest Problem]: Can't get past "Moving and Storing Mana" in the Tutorial Section

### ISSUE THREAD

**Issue by jb-99** [FTBTeam/FTB-University#87]
* What version of University: 1.3.0
* What quest: Moving and Storing Mana
* What is the problem: I can't bind the Mana Spreader to the Mana Pool.

Also, the quest called "Generating Mana" fails to flag the task "Fill the Petal Apothecary with the Water Bucket" as completed and is thus stuck in the default top-left position.

I've tried restarting the tutorial area several times through the GUI but the reset seems wrong, 'cause it leaves all the items in my inventory while giving this error message in chat "An unknown error occurred while attempting to perform this command"

In addition, immediately after loading into the tutorial, I get a error message in chat saying "Error in kubejs/detectors.js"

**Comment by aaronhowser1** [comment]
This is the University issue tracker

**Comment by jb-99** [comment]
Sorry, my bad! Had the wrong modpack opened and clicked on a wrong link...
