### ISSUE TITLE
[Modpack Problem]: Clearlag might be more problematic than helpful

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-University#9]
* What version of University: 1.0.0
* Describe the issue: Clearlag deletes everything, regardless of importance. Maybe remove it, maybe make it only delete vanilla items?

**Comment by quat1024** [comment]
I agree that clearlag is not a good thing to throw into a pack, I disabled it on my end. If you could make the script disabled by default that would be cool too. Especially in a modpack with Botania (which is all about littering items on the floor), also i don't think the ae2 certus quartz seeds are allowlisted which is kinda funny

**Comment by aaronhowser1** [comment]
Removed in 1.1

**Comment by MCSuperplayer** [comment]
I disabled it too after it deleted all my gear after i died in a cave :(
