### ISSUE TITLE
[Mod Request]: Cosmetic Armour

### ISSUE THREAD

**Issue by AutumnalModding** [FTBTeam/FTB-University#91]
* Mod Name: Cosmetic Armor Reworked
* Mod Dependencies: None found
* Mod License: MMPL (Minecraft Mod Public License)
* Mod Link: https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked
* Why you want it: Cosmetic Armour allows players to hide their armour, and also optionally wear a set of "cosmetic" armour, which grants no benefits, but is still rendered on the player model.

**Comment by ToastedPT** [comment]
Seconded, would like to see this be added
