### ISSUE TITLE
[Modpack Problem]: OTG Core needs to be deleted before new virsion will load

### ISSUE THREAD

**Issue by Iplay2L8** [FTBTeam/FTB-University#98]
* What version of University:1.1.0
* Describe the issue:Pack will not load Error Msg stating OTG core is not right version 
mod author notes in change log that Original OTG core v9.0 might need to be deleated after update.
Deleated the core mod and now pack will load.
 Edit: this happens in pack with save files/worlds  not in new install

**Comment by aaronhowser1** [comment]
This is an ftb app issue and is already being looked into

**Comment by aaronhowser1** [comment]
Fixed in 1.1.1
